name: canvas
description: A  Flutter  Canvas project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #多语言
  intl: ^0.18.0

  #多语言
  flutter_localizations:
    sdk: flutter

  flutter_apm: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  #多语言代码生成工具插件
  intl_generator: ^0.3.0

flutter:


  uses-material-design: true


  assets:
    - images/chair-alpha.png
    - images/ic_launcher.png

#多语言代码生成工具插件
flutter_intl:
  enabled: true